# Generated by Django 2.2.12 on 2020-09-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=30)),
                ('plan_amount', models.IntegerField()),
                ('plan_duration', models.IntegerField()),
            ],
        ),
    ]
