# Generated by Django 2.2.12 on 2020-09-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='contact',
            new_name='mobile',
        ),
    ]
